apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: recipes-ingress
  namespace: recipes
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: recipes-svc
      port:
        number: 8080
  tls:
    - hosts:
        - recipes

