apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: recipes
resources:
  - namespace.yaml
  - service-account.yaml
  - configmap-nginx.yaml
  - pvc.yaml
  - pvc-db.yaml
  - postgres-statefulset.yaml
  - svc-db.yaml
  - deployment.yaml
  - svc.yaml
  - cert.yaml
  - ingressroute-traefik.yaml
  - ingress-tailscale.yaml

