apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: commafeed
resources:
  - namespace.yaml
  - svc.yaml
  # pvc.yaml removed temporarily - will re-add with NFS storage class
  - deployment.yaml
  - cert.yaml
  - ingressroute-traefik.yaml
  - ingress-tailscale.yaml
  - ntfy-alert.yaml